# SQLite version 3.x
#
development:
  adapter: postgresql
  encoding: unicode
  database: bookandgo
  pool: 5
  username: postgres
  password: charles

test:
  adapter: postgresql
  encoding: unicode
  database: bookandgo
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: bookandgo_production
  pool: 5
  username: postgres
  password: postgres
